---
name: Apache2-UploadProgress
version: 0.2
author:
  - 'Christian Hansen <chansen@cpan.org>'
abstract: Track the progress and give realtime feedback of file uploads
license: perl
requires:
  Cache::FastMmap: 0
  HTTP::Headers::Util: 0
  Time::HiRes: 0
  mod_perl2: 2
  perl: 5.006
build_requires:
  Apache::Test: 1.12
  CGI: 3.08
provides:
  Apache2::UploadProgress:
    file: lib/Apache2/UploadProgress.pm
    version: 0.2
generated_by: Module::Build version 0.2612
